--- # Create VM on ESXi
- hosts: local
  gather_facts: false
  connection: local

  tasks:
  - name: Clone a template from New VM
    vmware_guest:
      hostname: 
      username: 
      password: 
      validate_certs: no
      datacenter: Ottawa
      state: present
      folder: Suj
      guest_id: centos64Guest
      name: centos7x64
      template: Centos-KS-AI
      is_template: true
    register: deploy

  - name: show deploy
    debug:
      msg: "{{ deploy }}"
      
