--- # Clone VM from template on ESXi
- hosts: local
  gather_facts: false
  connection: local

  vars_prompt:
    - name: "hostname"
      prompt: "Vcenter IP:"
      private: no
    - name: "username"
      prompt: "User Name:"
      private: no
    - name: "password"
      prompt: "Password:"
      private: yes
    - name: "esxi"
      prompt: "ESXi:"
      private: no
    - name: "datacenter"
      prompt: "DataCenter:"   
      private: no
    - name: "vmname"
      prompt: "VM Name:"   
      private: no
  tasks:
  - name: Clone vm from template VM
    vmware_guest:
      hostname: 10.203.137.201
      username: dslabs@vsphere.local
      password: Hqlocal1
      datacenter: Ottawa QA Server
      folder: Suraj
      template: centos7x64
      validate_certs: no
      name: CentosTMP
      state: poweredon
      guest_id: centos64Guest
      disk:
      - size_gb: 100
        type: thin
        datastore: R5-LDS03
      networks:
      - name: VM Network
        ip: 10.10.10.2
        netmask: 255.255.255.0
        gateway: 10.10.10.1
        dns_servers:
        - 8.8.8.8
        - 8.8.8.8
      hardware:
        memory_mb: 4096
        num_cpus: 2
      customization:
        dns_servers:
        - 8.8.8.8
        - 8.8.8.8
