--- # Create VM on ESXi
- hosts: local
  gather_facts: false
  connection: local

  tasks:
  - name: Adding VM to dynamic Inventory
    add_host:
      name: Centos-KS-AI
      group: centos
      ansible_ssh_host: 10.203.202.161
      ansible_ssh_port: 22
      inventory_dir: ''
      ansible_ssh_user: root
      ansible_ssh_pass: 12345
      ansible_become_user: root
      ansible_become_pass: 12345
      ansible_ssh_extra_args: '-o StrickHostKeyChecking=no'
      registe: ts
  - name: run command
    ansible_ssh_host: 10.203.202.161
    ansible_ssh_port: 22
    ansible_ssh_user: root
    ansible_ssh_pass: 12345
    command: ping -c 4  10.203.202.161
    register: ping
  - debug: var=ts
  - debug: var=ping
