--- # Create VM on ESXi
- hosts: local
  gather_facts: false
  connection: local

  vars_prompt:
    - name: "hostname"
      prompt: "Vcenter IP:"
      private: no
    - name: "username"
      prompt: "User Name:"
      private: no
    - name: "password"
      prompt: "Password:"
      private: yes
    - name: "esxi"
      prompt: "ESXi:"
      private: no
    - name: "datacenter"
      prompt: "DataCenter:"   
      private: no
    - name: "vmname"
      prompt: "VM Name:"   
      private: no
  tasks:

  - name: Create the VM
    vmware_guest:
      hostname: '{{ hostname  }}'
      username: '{{ username  }}'
      password: '{{ password  }}'
      validate_certs: no
      esxi_hostname: '{{ esxi }}'
      datacenter: '{{ datacenter }}'
      folder: Suraj
      name: '{{ vmname }}'
      state: poweredon
      guest_id: centos64Guest
      disk:
      - size_gb: 100
        type: thin
        datastore: R5-LDS03
      networks:
      - name: VM Network
        ip: 10.10.10.2
        netmask: 255.255.255.0
        gateway: 10.10.10.1
        dns_servers:
        - 8.8.8.8
        - 8.8.8.8
      hardware:
        memory_mb: 4096
        num_cpus: 2
      cdrom:
        type: "iso"
        iso_path: "[R5-LDS03] ISO/centos7-ks-Final.iso"
      customization:
        dns_servers:
        - 8.8.8.8
        - 8.8.8.8
    delegate_to: localhost
    register: newvm
  - name: wait_for_boot
    wait_for:
      host: "{{ newvm.instance.ipv4 }}"
      port: 22
      delay: 60
      timeout: 500
      state: started
  - name: IP Address
    debug:
      msg: "{{ newvm.instance.ipv4 }} {{ vmname  }}"
