--- # Create VM on ESXi
- hosts: local
  gather_facts: false
  connection: local

  tasks:
  - name: Create VM from the Template
    vmware_guest:
      hostname: 10.203.137.201
      username: dslabs@vsphere.local
      password: Hqlocal1
      validate_certs: no
      esxi_hostname: 10.203.137.210
      datacenter: DS-Labs Ottawa
      folder: Discovered virtual machine
      template: AI - ubuntu 16.04
      name: ubuntu-Template
      state: poweredon
      disk:
      - size_gb: 100
        type: thin
        datastore: 2 TB HDD
      networks:
      - name: VM Network
        ip: 10.10.10.2
        netmask: 255.255.255.0
        gateway: 10.10.10.1
        dns_servers:
        - 8.8.8.8
        - 8.8.8.8
      hardware:
        memory_mb: 4096
        num_cpus: 2
      customization:
        dns_servers:
        - 8.8.8.8
        - 8.8.8.8
