--- # Create VM on ESXi
- hosts: local
  gather_facts: false
  connection: local

  tasks:
  - name: Download Application
    get_url:
      url: https://files.trendmicro.com/products/deepsecurity/en/11.0/Agent-RedHat_EL7-11.0.0-211.x86_64.zip
      dest: ~/Downloads/Agent-RedHat_EL7-11.0.0-211.x86_64.zip
      mode: 0777
    delegate_to: 10.203.202.161

  - name: Unarchive the Application
    unarchive:
      src: ~/Downloads/Agent-RedHat_EL7-11.0.0-211.x86_64.zip
      dest: ~/Downloads/unarchive
      remote_src: yes
    delegate_to: 10.203.202.161

  - name: Install the -RPM-
    yum:
      name: /root/Downloads/unarchive/Agent-Core-RedHat_EL7-11.0.0-211.x86_64.rpm
      state: latest
    delegate_to: 10.203.202.161

  - name: start APP Servicei
    command: systemctl start ds_agent
    register: result
    delegate_to: 10.203.202.161

  - debug:
      msg: "{{ result }}"
  - name: Verify APP Service
    command: systemctl status ds_agent
    register: result
    delegate_to: 10.203.202.161

  - debug:
      msg: "{{ result.stdout_lines[2] }}"
    
