--- # Create VM on ESXi
- hosts: local
  gather_facts: false
  connection: local

  tasks:
  - name: Check the Template Exist
    vmware_guest_find:
      hostname: 
      username: 
      password: 
      validate_certs: no
      name: centos7x64
    register: found
  - debug: var=found
