--- # Create VM on ESXi
- hosts: local
  gather_facts: false
  connection: local

  tasks:
  - name: find folder
    vmware_guest_find:
      hostname: 10.203.137.201
      username: dslabs@vsphere.local
      password: Hqlocal1
      validate_certs: no
      uuid: 564d4cdc-411a-00ff-8bfa-49f0cd6e1b49
    register: vm_folder
  - debug: var=vm_folder
