--- # Create VM on ESXi
- hosts: local
  gather_facts: false
  connection: local

  tasks:
  - name: Gather Facts Of All Vms in virtual center or ESXi
    local_action:
      module: vmware_vm_facts
      hostname: 10.203.137.201
      username: dslabs@vsphere.local
      password: Hqlocal1
      validate_certs: False
    register: facts
  - name: Check if th VM  name exists
    debug:
       msg: "{{ facts|['uuid'] }}"
    ignore_errors: true
    register: uuid
  - debug: var=uuid
