--- # Create VM on ESXi
- hosts: local
  gather_facts: false
  connection: local

  tasks:
  - name: Install APP
    yum: pkg=lynx state=latest
    delegate_to: 10.203.202.161
  - name: start service
    service: name=httpd state=restarted
    delegate_to: 10.203.202.161
