---
- name: Create VM and Install OS using pyVmomi
  hosts: localhost
  gather_facts: False
  connection: local

  #Virtual machine name "use input"
  vars_prompt:
    - name: "vmname"
      prompt: "VM Name:"
      private: no

  #Variables - should be dynamic based on the resources of vcenter hosts
  #and we can use external file as a variable
  vars:
    vcenter_hostname: ''
    vcenter_user: ''
    vcenter_pass: ''
    vmtemplate: ''
    new_port: 22
    inventory_dir: '/etc/ansible/hosts'
    ansible_ssh_user: 'root'
    ansible_ssh_pass: '12345'
    ansible_become_user: 'root'
    ansible_become_pass: '12345'
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
    esxi: ''
    datacenter: ''
  tasks:
  - name: Create the VM
    vmware_guest:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_user  }}'
      password: '{{ vcenter_pass }}'
      validate_certs: False
      esxi_hostname: '{{ esxi }}'
      datacenter: '{{ datacenter }}'
      folder: Suraj
      name: '{{ vmname }}'
      state: poweredon
      guest_id: centos64Guest
      disk:
      - size_gb: 100
        type: thin
        datastore: R5-LDS03
      networks:
      - name: VM Network
        type: dhcp
      hardware:
        memory_mb: 4096
        num_cpus: 2
      cdrom:
        type: "iso"
        iso_path: "[R5-LDS03] ISO/centos7-ks-Final.iso"
      customization:
        dns_servers:
        - 8.8.8.8
        - 8.8.8.8
    register: newvmdeploy
    #when: uuid|failed
  - debug: var=newvmdeploy

